#!/bin/sh

datadir=/usr/share
idxdir=$datadir/bP/indexhtml
docdir=$datadir/doc/HTML

[ -d $idxdir ] || exit 1
[ -d $docdir ] || exit 1

function get() {
    wget -q -N -O $docdir/index.tmp $1 && \
	tar jxf $docdir/index.tmp -C $docdir && exit 0
}

if [ -r /etc/sysconfig/i18n ] ; then
    . /etc/sysconfig/i18n
    if [ -n "$LANGUAGE" ]; then
        LISTLANG="`echo $LANGUAGE | tr ':' ' '`" ;
    else
        if [ -n "$LANG" ]; then
            LISTLANG="$LANG"
        fi
    fi
fi

(

for i in $LISTLANG en; do
    if [ -r $idxdir/index-$i.html ]; then
        cp -pf $idxdir/index-$i.html $docdir/index.html
        break
    else
        lang=`echo $i | cut -b-2`
        if [ -r $idxdir/index-$lang.html ]; then
            cp -pf $idxdir/index-$lang.html $docdir/index.html
            break;
        fi
    fi
done
) &

# update-indexhtml ends here
